### ISSUE TITLE
upload document list

### ISSUE THREAD

**Issue by hsn-rahmani** [Bonitasoft-Community/file-upload-download-example#1]
Hi every body,
Please improve this example by using a document list to save and transfer more than one uploaded file in the process (if its possible in the first initialization task),

Thanks & Regards.

**Comment by amottier** [comment]
Latest release ([7.1.5-1.1.0](https://github.com/Bonitasoft-Community/file-upload-download-example/releases/tag/7.1.5-1.1.0)) of this example now demonstrate usage of mulitple document as well as upload in instantiation form.
