### ISSUE TITLE
Mime Type application/pdf

### ISSUE THREAD

**Issue by DRAKUN** [Bonitasoft-Community/file-upload-download-example#3]
Bonjour,

J'aimerais limiter le type de fichier a charger sur mon processus en PDF uniquement.
J'ai ajouter une contrainte et j'ai définie sa valeur a :

> Nom : OnlyPdfDocument
> expression : return pjDemandeCompteDocumentInput.getContentType() == "application/pdf" ? true : false
> Message d'erreur : Veuillez charger un document de type PDF 

Sur mon formulaire j'arrive toujours a charger tout type de document.
Someone can help me

**Comment by amottier** [comment]
Example has been updated to illustrate how to only accept PDF file upload.
