### ISSUE TITLE
Call fom Rest API

### ISSUE THREAD

**Issue by camilocastellanosg** [Bonitasoft-Community/file-upload-download-example#5]
Hi. I´ve tried to call this proces from bonita REST API . but it doesn´t work. can you share me the guide to try it ?

thanks

**Comment by amottier** [comment]
Sorry about this late response.

Actually this process example is not attend to be instantiated using Bonita Engine API.

If you are interested in using Bonita Engine REST API I recommend to watch the [video](https://www.youtube.com/watch?v=PVp5lu8EGp4) I published about it.

Also if you need assistance with REST API I recommend to post on Bonita [community Q&A](https://community.bonitasoft.com/questions-and-answers).

I'm closing this issue. Please add a comment if there is any specific problem with this process example.

Thanks
